routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'IndexController@index');


Route::get('/articles', 'NewsController@news');
Route::get('/news/{id}', 'NewsController@news_detalis');
Route::get('/news-archive', 'NewsController@news_archive');
Route::get('/news-search', 'NewsController@news_search');


Route::get('/activity', 'NewsController@activity');
Route::get('/activities', 'NewsController@activities');
Route::get('/activity/{id}', 'NewsController@activity_detalis');
Route::get('/programs', 'NewsController@programs');
Route::get('/programs/{id}', 'NewsController@program_detalis');
Route::get('/galleries', 'GalleryController@galleries');
Route::get('/gallery/{id}', 'GalleryController@gallery_detalis');
Route::get('/videos/{id}', 'GalleryController@video_detalis');
Route::get('/game-categories', 'GameController@game_categories');
Route::get('/game-categories/{id}', 'GameController@games');
Route::get('/game/{id}', 'GameController@games_detalis');
Route::get('/partners', 'PartnersController@partners');
Route::get('/partner/{id}', 'PartnersController@partner_detalis');
Route::get('/about', 'AboutController@about');
Route::get('/athletes', 'AthleteController@index');
Route::get('/athlete/{id}', 'AthleteController@detailis');
Route::get('/athletes/filters', 'AthleteController@athlete_filter');
Route::get('/sports', 'AthleteController@sports');

Route::get('/locale/{lang}', 'IndexController@setLocale');
Route::post('/subscribe', 'ContactController@subscribe');

// Route::get('/test_view', 'IndexController@test');
// Route::get('/tokyo2020', function(){
//     return view('front.tokyo2020');
// });

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::resource('gallery' ,'admin\GalleryController');
    Route::get('/imgs/{id}/del' ,'admin\GalleryController@del');
    Route::post('/update_img' ,'admin\GalleryController@update_img');
    Route::post('/create_img' ,'admin\GalleryController@create_img');

    Route::resource('videogallery' ,'admin\VideoGalleryController');
    Route::resource('publications' ,'admin\PublicationsController');

    Route::resource('news' ,'admin\NewsController');
    Route::get('/news_imgs/{id}/del' ,'admin\NewsController@del');
    Route::post('/news_update_img' ,'admin\NewsController@update_img');
    Route::post('/news_create_img' ,'admin\NewsController@create_img');

    Route::resource('/federations' ,'admin\FederationsController');
    Route::resource('/documents' ,'admin\DocumentsController');
    Route::resource('/document_groups' ,'admin\DocumentGroupsController');
    Route::resource('/sponsors' ,'admin\SponsorsController');
    Route::resource('/partners' ,'admin\PartnersController');

    Route::resource('/persons' ,'admin\PersonsController');
    Route::get('/index_status','admin\PersonsController@index_status');
    Route::get('/icra_komite','admin\PersonsController@icra_komite');

    Route::resource('/history' ,'admin\HisrtoryController');
    Route::resource('/committees' ,'admin\CommitteeController');

    Route::resource('/bash_meclis' ,'admin\BasMeclisController');
    Route::get('/meclis/{id}/del' ,'admin\BasMeclisController@del');
    Route::get('/meclis/{id}/terkib_edit' ,'admin\BasMeclisController@terkib_edit');
    Route::get('/meclis/{id}/create' ,'admin\BasMeclisController@creat_ter');
    Route::post('/meclis/terkib_update' ,'admin\BasMeclisController@terkib_update');
    Route::post('/meclis/terkib_create' ,'admin\BasMeclisController@terkib_create');

    Route::resource('/institutions' ,'admin\InstitutionsController');
    Route::resource('/members' ,'admin\MembersController');

    Route::resource('/game_categories' ,'admin\GameCategoriesController');
    Route::resource('/sports' ,'admin\SportsController');
    Route::resource('/games' ,'admin\GamesController');
    Route::get('/game_status' ,'admin\GamesController@game_status');

    Route::resource('/executive' ,'admin\IcrayyeController');
    Route::resource('/game_statistics' ,'admin\GameStatisticsController');
    Route::resource('/athlete' ,'admin\AthleteController');
    Route::get('/athlete_kommisia' ,'admin\AthleteController@kommisia');
    Route::get('/significance_status' ,'admin\AthleteController@significance_status');

    Route::resource('/tournaments' ,'admin\TurnirController');
    Route::resource('/athlete_statistics' ,'admin\AthleteStatisticsController');
    Route::get('/tournaments_type' ,'admin\AthleteStatisticsController@tournaments_type');
});

app/Publications.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Publications extends Model
{
  protected $table = 'publications';
  protected $primaryKey = 'id';
  public $timestamps = false;
  protected $fillable = [
    'id','publication_name','publication_name_en','publication_file','publication_thumbnail','author_name','author_name_en'
  ];
}

app/Http/Controllers/admin/PublicationsController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Publications;
use Session;
use File;
class PublicationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $publications = Publications::all();

        return view('admin.publications.index',compact('publications'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.publications.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

      $thumbnail1 = $request->file('publication_thumbnail');
      $thumbnail = time().'.'.$thumbnail1->getClientOriginalName();
      $thumbnail1->move(public_path('uploads'), $thumbnail);

      $p_file1 = $request->file('publication_file');
      $p_file = time().'.'.$p_file1->getClientOriginalName();
      $p_file1->move(public_path('uploads'), $p_file);


        Publications::create([
            'publication_name'=>$request['publication_name'],
            'publication_name_en'=>$request['publication_name_en'],
            'author_name'=>$request['author_name'],
            'author_name_en'=>$request['author_name_en'],
            'publication_file'=>$p_file,
            'publication_thumbnail'=>$thumbnail,
        ]);
      Session::flash('success','Kontent əlavə edildi');
      return redirect('/admin/publications');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $publication = Publications::find($id);

        return view('admin.publications.edit',compact('publication'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $publication = Publications::find($id);

      if($request->file('publication_thumbnail')){

         $del = $publication->publication_thumbnail;
          $image_path = public_path().'/uploads/'.$del;
          if(File::exists($image_path)) {
            File::delete($image_path);
          }

        $cover1 = $request->file('publication_thumbnail');
        $cover = time().'.'.$cover1->getClientOriginalName();
        $cover1->move(public_path('uploads'), $cover);

        $publication->update([
          'publication_thumbnail'=>$cover,
        ]);
      }

      if($request->file('publication_file')){

         $del = $publication->publication_file;
          $image_path = public_path().'/uploads/'.$del;
          if(File::exists($image_path)) {
            File::delete($image_path);
          }

        $P_file1 = $request->file('publication_file');
        $P_file = time().'.'.$P_file1->getClientOriginalName();
        $P_file1->move(public_path('uploads'), $P_file);

        $publication->update([
          'publication_file'=>$P_file,
        ]);
      }

      $publication->update([
        'publication_name'=>$request['publication_name'],
        'publication_name_en'=>$request['publication_name_en'],
        'author_name'=>$request['author_name'],
        'author_name_en'=>$request['author_name_en'],
      ]);
      Session::flash('success','Kontent redaktə edildi');
      return redirect('/admin/publications');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $publication = Publications::find($id);

      $del = $publication->publication_file;
       $image_path = public_path().'/uploads/'.$del;
       if(File::exists($image_path)) {
         File::delete($image_path);
       }

       $del1 = $publication->publication_file;
        $image_path1 = public_path().'/uploads/'.$del1;
        if(File::exists($image_path1)) {
          File::delete($image_path1);
        }

      $publication->delete();
      Session::flash('danger','Kontent silindi');
      return redirect('/admin/publications');
    }
}

resources/views/admin/publications/create.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">

            <div class="header">
            </div>
            <div class="body table-responsive">
              <form class="form-horizontal" action="{{ route('publications.store') }}" method="POST" enctype="multipart/form-data">
                @csrf


                <div class="col-md-6">
                  <p><b>Nəşrin adı  </b><span style="color:red;">* </span></p>
                  <input type="text" name="publication_name"  class="form-control"  required>
                </div>
                <div class="col-md-6">
                  <p><b>Nəşrin adı  (EN)</b><span style="color:red;"> </span></p>
                  <input type="text" name="publication_name_en"  class="form-control"  >
                </div>
                <div class="col-md-6">
                  <p><b>Müəllif</b><span style="color:red;">* </span></p>
                  <input type="text" name="author_name"  class="form-control"  required>
                </div>
                <div class="col-md-6">
                  <p><b>Müəllif (en) <span style="color:red"></span></b></p>
                  <input type="text" name="author_name_en"  class="form-control"  >
                </div>
                <div class="col-md-6">
                  <p><b>Thumbnail (Fayl ölçüsü max 1024kb olmalıdır (min:150x190))</b><span style="color:red;">* </span></p>
                  <input type="file" name="publication_thumbnail"  class="form-control"  required  id="logo">
                </div>
                <div class="col-md-6">
                  <p><b>Nəşrin elektron forması (PDF) </b><span style="color:red;">* </span></p>
                  <input type="file" name="publication_file"  class="form-control"  required >
                </div>





                <div class="col-md-10">
                  <button type="submit" class="btn btn-success">
                      Əlavə Et
                    </button>
                </div>
              </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$('#logo').bind('change', function(event) {
  if ($(this).context.files[0].size/ 1024 > 1024) {
    $(this).replaceWith($(this).val('').clone(true));
    alert('Fayl 1024kb dan böyükdür');
  }
});
</script>
@endsection

resources/views/admin/publications/edit.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">

            <div class="header">
            </div>
            <div class="body table-responsive">
              <form class="form-horizontal" action="{{ route('publications.update', $publication->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                  <input type="hidden" name="_method" value="PATCH">
                  <div class="col-md-6">
                    <p><b>Nəşrin adı  </b><span style="color:red;">* </span></p>
                    <input type="text" name="publication_name"  class="form-control"  required value={{$publication->publication_name}}>
                  </div>
                  <div class="col-md-6">
                    <p><b>Nəşrin adı  (EN)</b><span style="color:red;"> </span></p>
                    <input type="text" name="publication_name_en"  class="form-control"   value={{$publication->publication_name_en}}>
                  </div>
                  <div class="col-md-6">
                    <p><b>Müəllif</b><span style="color:red;">* </span></p>
                    <input type="text" name="author_name"  class="form-control"  required value={{$publication->author_name}}>
                  </div>
                  <div class="col-md-6">
                    <p><b>Müəllif (en) <span style="color:red"></span></b></p>
                    <input type="text" name="author_name_en"  class="form-control"  value={{$publication->author_name_en}}>
                  </div>
                <div class="col-md-6" >
                  <p><b>Thumbnail </b><br><span style="color:red;">(Fayl ölçüsü max 1024kb olmalıdır (min:150x190))</span></p>
                  <input type="file" name="publication_thumbnail"  class="form-control" id="cover" style="display:n one;">
                  <div class="col-md-6" style="padding-top:40px;">
                    <label for="cover"><img src="/uploads/{{$publication->publication_thumbnail}}" class="img-responsive" style="cursor:pointer"/></label>
                    <!-- <p><b>İşə aid şəkillər (Eyni anda max 10 şəkil əlavə edilə bilər)</b></p>
                    <input type="file" name="img_src[]" multiple class="form-control"> -->
                  </div>
                </div>
                <div class="col-md-6" >
                  <p><b>Nəşrin elektron forması (PDF) </b></p>
                  <input type="file" name="publication_file"  class="form-control"  style="display:n one;">
                  <div class="col-md-6" style="padding-top:40px;">
                      <a target="_blank" href="/uploads/{{$publication->publication_file}}">{{$publication->publication_file}}</a>
                  </div>
                </div>


                <div class="col-md-10">
                  <button type="submit" class="btn btn-success">
                    Redaktə Et
                    </button>
                </div>
              </form>


            </div>
        </div>
    </div>
</div>

     <script type="text/javascript">
    $('#cover, #intro').bind('change', function(event) {
      if ($(this).context.files[0].size/ 1024 > 1024) {
        $(this).replaceWith($(this).val('').clone(true));
        alert('Fayl 1024kb dan böyükdür');
      }
    });
     </script>
@endsection

resources/views/admin/publications/index.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            @if(Session::has('mesaj'))
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                {{ Session::get('mesaj') }}
            </div>
            @endif
            <div class="header">
                <h2>
                <a href="{{ route('publications.create') }}"><button type="button" class="btn btn-success btn-circle waves-effect waves-circle waves-float">
                    <i class="material-icons">add</i>
                </button></a>
            </div>
            <div class="body table-responsive">


              <table class="table table-hover">
                  <thead>
                      <tr>
                          <th>Nəşrin adı </th>
                          <th>Müəllif</th>
                          <th><span class="text-danger">Sil</span> / <span class="text-success">Redaktə et</span></th>
                      </tr>
                  </thead>
                  <tbody>
                      @foreach($publications as $publication)
                      <tr>

                          <td>{{ $publication->publication_name }}</td>
                          <td>{{ $publication->author_name }}</td>

                          <td>
                            <button value="{{$publication->id}}" class="btn btn-danger remove">Sil</button>
                              <form id="remove{{$publication->id}}" action="{{ route('publications.destroy', $publication->id) }}" method="post" style="display: none;">
                                  {{ csrf_field() }}
                                  <input type="hidden" name="_method" value="DELETE">
                                  <input type="submit" value="Sil" class="btn btn-danger">
                              </form>
                              <a href="{{ route('publications.edit', $publication->id) }}" class="btn-success btn">Redaktə et</a>
                          </td>
                      </tr>
                      @endforeach
                  </tbody>
              </table>
            </div>
        </div>
    </div>
</div>
<script>

    $('.remove').on('click', function(){
        var val = $(this).val();
        const swalWithBootstrapButtons = Swal.mixin({
        customClass: {
        confirmButton: 'btn btn-success',
        cancelButton: 'btn btn-danger'
         },
      buttonsStyling: false
    })
    
    swalWithBootstrapButtons.fire({
      title: 'Əminsiniz?',
      text: "Nəşr silinəcək",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonText: 'Bəli, Sil!',
      cancelButtonText: 'Ləğv et!',
      reverseButtons: true
    }).then((result) => {
      if (result.isConfirmed) {
        $('#remove'+val+'').submit();
       
      } else if (
        /* Read more about handling dismissals below */
        result.dismiss === Swal.DismissReason.cancel
      ) {
        swalWithBootstrapButtons.fire(
          'Ləğv edildi',
        )
      }
    })
    });
    </script>
@endsection