routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'IndexController@index');


Route::get('/articles', 'NewsController@news');
Route::get('/news/{id}', 'NewsController@news_detalis');
Route::get('/news-archive', 'NewsController@news_archive');
Route::get('/news-search', 'NewsController@news_search');


Route::get('/activity', 'NewsController@activity');
Route::get('/activities', 'NewsController@activities');
Route::get('/activity/{id}', 'NewsController@activity_detalis');
Route::get('/programs', 'NewsController@programs');
Route::get('/programs/{id}', 'NewsController@program_detalis');
Route::get('/galleries', 'GalleryController@galleries');
Route::get('/gallery/{id}', 'GalleryController@gallery_detalis');
Route::get('/videos/{id}', 'GalleryController@video_detalis');
Route::get('/game-categories', 'GameController@game_categories');
Route::get('/game-categories/{id}', 'GameController@games');
Route::get('/game/{id}', 'GameController@games_detalis');
Route::get('/partners', 'PartnersController@partners');
Route::get('/partner/{id}', 'PartnersController@partner_detalis');
Route::get('/about', 'AboutController@about');
Route::get('/athletes', 'AthleteController@index');
Route::get('/athlete/{id}', 'AthleteController@detailis');
Route::get('/athletes/filters', 'AthleteController@athlete_filter');
Route::get('/sports', 'AthleteController@sports');

Route::get('/locale/{lang}', 'IndexController@setLocale');
Route::post('/subscribe', 'ContactController@subscribe');

// Route::get('/test_view', 'IndexController@test');
// Route::get('/tokyo2020', function(){
//     return view('front.tokyo2020');
// });

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::resource('gallery' ,'admin\GalleryController');
    Route::get('/imgs/{id}/del' ,'admin\GalleryController@del');
    Route::post('/update_img' ,'admin\GalleryController@update_img');
    Route::post('/create_img' ,'admin\GalleryController@create_img');

    Route::resource('videogallery' ,'admin\VideoGalleryController');
    Route::resource('publications' ,'admin\PublicationsController');

    Route::resource('news' ,'admin\NewsController');
    Route::get('/news_imgs/{id}/del' ,'admin\NewsController@del');
    Route::post('/news_update_img' ,'admin\NewsController@update_img');
    Route::post('/news_create_img' ,'admin\NewsController@create_img');

    Route::resource('/federations' ,'admin\FederationsController');
    Route::resource('/documents' ,'admin\DocumentsController');
    Route::resource('/document_groups' ,'admin\DocumentGroupsController');
    Route::resource('/sponsors' ,'admin\SponsorsController');
    Route::resource('/partners' ,'admin\PartnersController');

    Route::resource('/persons' ,'admin\PersonsController');
    Route::get('/index_status','admin\PersonsController@index_status');
    Route::get('/icra_komite','admin\PersonsController@icra_komite');

    Route::resource('/history' ,'admin\HisrtoryController');
    Route::resource('/committees' ,'admin\CommitteeController');

    Route::resource('/bash_meclis' ,'admin\BasMeclisController');
    Route::get('/meclis/{id}/del' ,'admin\BasMeclisController@del');
    Route::get('/meclis/{id}/terkib_edit' ,'admin\BasMeclisController@terkib_edit');
    Route::get('/meclis/{id}/create' ,'admin\BasMeclisController@creat_ter');
    Route::post('/meclis/terkib_update' ,'admin\BasMeclisController@terkib_update');
    Route::post('/meclis/terkib_create' ,'admin\BasMeclisController@terkib_create');

    Route::resource('/institutions' ,'admin\InstitutionsController');
    Route::resource('/members' ,'admin\MembersController');

    Route::resource('/game_categories' ,'admin\GameCategoriesController');
    Route::resource('/sports' ,'admin\SportsController');
    Route::resource('/games' ,'admin\GamesController');
    Route::get('/game_status' ,'admin\GamesController@game_status');

    Route::resource('/executive' ,'admin\IcrayyeController');
    Route::resource('/game_statistics' ,'admin\GameStatisticsController');
    Route::resource('/athlete' ,'admin\AthleteController');
    Route::get('/athlete_kommisia' ,'admin\AthleteController@kommisia');
    Route::get('/significance_status' ,'admin\AthleteController@significance_status');

    Route::resource('/tournaments' ,'admin\TurnirController');
    Route::resource('/athlete_statistics' ,'admin\AthleteStatisticsController');
    Route::get('/tournaments_type' ,'admin\AthleteStatisticsController@tournaments_type');
});

app/History.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class History extends Model
{
  protected $table = 'history';
  protected $primaryKey = 'id';
  public $timestamps = false;
  protected $fillable = [
    'id',
    'history',
    'history_en',

  ];
}

resources/views/admin/history/create.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">

            <div class="header">
            </div>
            <div class="body table-responsive">
              <form class="form-horizontal" action="{{ route('history.store') }}" method="POST" enctype="multipart/form-data">
                @csrf


                <div class="col-md-12">
                  <p><b>Tarix<span style="color:red">*</span></b></p>
                  <textarea name="history" rows="8" cols="80" required id="article-ckeditor2"></textarea>
                </div>
                <div class="col-md-12">
                  <p><b>Tarix (en)<span style="color:red"></span></b></p>
                  <textarea name="history_en" rows="8" cols="80"  id="article-ckeditor3"></textarea>
                </div>
                <div class="col-md-10">
                  <button type="submit" class="btn btn-success">
                      Əlavə Et
                    </button>
                </div>
              </form>
            </div>
        </div>
    </div>
</div>
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>

<script type="text/javascript">

  var CSRFToken = $('meta[name="csrf-token"]').attr('content');

var options = {
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token='+CSRFToken,
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='+CSRFToken
  };
  CKEDITOR.replace( 'article-ckeditor2', options );
  CKEDITOR.replace( 'article-ckeditor3', options );

  $("form").submit( function(e) {

     var messageLength2 = CKEDITOR.instances['article-ckeditor2'].getData().replace(/<[^>]*>/gi, '').length;
     // var messageLength3 = CKEDITOR.instances['article-ckeditor3'].getData().replace(/<[^>]*>/gi, '').length;
     if( messageLength2 < 1) {
         alert( 'İşarələnmiş bütün xanalar doldurulmalıdır' );
         e.preventDefault();
     }

 });


</script>
@endsection

resources/views/admin/history/edit.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">

            <div class="header">
            </div>
            <div class="body table-responsive">
              <form class="form-horizontal" action="{{ route('history.update', $history->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                  <input type="hidden" name="_method" value="PATCH">

                  <div class="col-md-12">
                    <p><b>Tarix<span style="color:red">*</span></b></p>
                    <textarea name="history" rows="8" cols="80" required id="article-ckeditor2">{{$history->history}}</textarea>
                  </div>
                  <div class="col-md-12">
                    <p><b>Tarix (en)<span style="color:red"></span></b></p>
                    <textarea name="history_en" rows="8" cols="80"  id="article-ckeditor3">{{$history->history_en}}</textarea>
                  </div>


                <div class="col-md-10">
                  <button type="submit" class="btn btn-success">
                    Redaktə Et
                    </button>
                </div>
              </form>


            </div>
        </div>
    </div>
</div>

<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script type="text/javascript">
var CSRFToken = $('meta[name="csrf-token"]').attr('content');

var options = {
  filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
  filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token='+CSRFToken,
  filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
  filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='+CSRFToken
};
CKEDITOR.replace( 'article-ckeditor2', options );
CKEDITOR.replace( 'article-ckeditor3', options );

$("form").submit( function(e) {

   var messageLength2 = CKEDITOR.instances['article-ckeditor2'].getData().replace(/<[^>]*>/gi, '').length;
   // var messageLength3 = CKEDITOR.instances['article-ckeditor3'].getData().replace(/<[^>]*>/gi, '').length;
   if( messageLength2 < 1) {
       alert( 'İşarələnmiş bütün xanalar doldurulmalıdır' );
       e.preventDefault();
   }

});

     </script>
@endsection

resources/views/admin/history/index.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            @if(Session::has('success'))
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                {{ Session::get('success') }}
            </div>
            @endif
            <div class="header">
                <h2>
                <a href="{{ route('history.create') }}"><button type="button" class="btn btn-success btn-circle waves-effect waves-circle waves-float">
                    <i class="material-icons">add</i>
                </button></a>
            </div>
            <div class="body table-responsive">


              <table class="table table-hover">
                  <thead>
                      <tr>
                          <th>Tarix</th>
                          <th><span class="text-danger">Sil</span> / <span class="text-success">Redaktə et</span></th>
                      </tr>
                  </thead>
                  <tbody>
                      @foreach($historys as $his)
                      <tr>
                          <td>
                          <?php $texts = explode(" ", $his->history); ?>
                          <?php for ($i=0; $i <count($texts)/10 ; $i++) {  ?> {!! $texts[$i] !!} <?php } ?>
                          </td>
                          <td>
                              <form action="{{ route('history.destroy', $his->id) }}" method="post" style="display: initial;">
                                  {{ csrf_field() }}
                                  <input type="hidden" name="_method" value="DELETE">
                                  <input type="submit" value="Sil" class="btn btn-danger">
                              </form>
                              <a href="{{ route('history.edit', $his->id) }}" class="btn-success btn">Redaktə et</a>
                          </td>
                      </tr>
                      @endforeach
                  </tbody>
              </table>
            </div>
        </div>
    </div>
</div>

@endsection