routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'IndexController@index');


Route::get('/articles', 'NewsController@news');
Route::get('/news/{id}', 'NewsController@news_detalis');
Route::get('/news-archive', 'NewsController@news_archive');
Route::get('/news-search', 'NewsController@news_search');


Route::get('/activity', 'NewsController@activity');
Route::get('/activities', 'NewsController@activities');
Route::get('/activity/{id}', 'NewsController@activity_detalis');
Route::get('/programs', 'NewsController@programs');
Route::get('/programs/{id}', 'NewsController@program_detalis');
Route::get('/galleries', 'GalleryController@galleries');
Route::get('/gallery/{id}', 'GalleryController@gallery_detalis');
Route::get('/videos/{id}', 'GalleryController@video_detalis');
Route::get('/game-categories', 'GameController@game_categories');
Route::get('/game-categories/{id}', 'GameController@games');
Route::get('/game/{id}', 'GameController@games_detalis');
Route::get('/partners', 'PartnersController@partners');
Route::get('/partner/{id}', 'PartnersController@partner_detalis');
Route::get('/about', 'AboutController@about');
Route::get('/athletes', 'AthleteController@index');
Route::get('/athlete/{id}', 'AthleteController@detailis');
Route::get('/athletes/filters', 'AthleteController@athlete_filter');
Route::get('/sports', 'AthleteController@sports');

Route::get('/locale/{lang}', 'IndexController@setLocale');
Route::post('/subscribe', 'ContactController@subscribe');

// Route::get('/test_view', 'IndexController@test');
// Route::get('/tokyo2020', function(){
//     return view('front.tokyo2020');
// });

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::resource('gallery' ,'admin\GalleryController');
    Route::get('/imgs/{id}/del' ,'admin\GalleryController@del');
    Route::post('/update_img' ,'admin\GalleryController@update_img');
    Route::post('/create_img' ,'admin\GalleryController@create_img');

    Route::resource('videogallery' ,'admin\VideoGalleryController');
    Route::resource('publications' ,'admin\PublicationsController');

    Route::resource('news' ,'admin\NewsController');
    Route::get('/news_imgs/{id}/del' ,'admin\NewsController@del');
    Route::post('/news_update_img' ,'admin\NewsController@update_img');
    Route::post('/news_create_img' ,'admin\NewsController@create_img');

    Route::resource('/federations' ,'admin\FederationsController');
    Route::resource('/documents' ,'admin\DocumentsController');
    Route::resource('/document_groups' ,'admin\DocumentGroupsController');
    Route::resource('/sponsors' ,'admin\SponsorsController');
    Route::resource('/partners' ,'admin\PartnersController');

    Route::resource('/persons' ,'admin\PersonsController');
    Route::get('/index_status','admin\PersonsController@index_status');
    Route::get('/icra_komite','admin\PersonsController@icra_komite');

    Route::resource('/history' ,'admin\HisrtoryController');
    Route::resource('/committees' ,'admin\CommitteeController');

    Route::resource('/bash_meclis' ,'admin\BasMeclisController');
    Route::get('/meclis/{id}/del' ,'admin\BasMeclisController@del');
    Route::get('/meclis/{id}/terkib_edit' ,'admin\BasMeclisController@terkib_edit');
    Route::get('/meclis/{id}/create' ,'admin\BasMeclisController@creat_ter');
    Route::post('/meclis/terkib_update' ,'admin\BasMeclisController@terkib_update');
    Route::post('/meclis/terkib_create' ,'admin\BasMeclisController@terkib_create');

    Route::resource('/institutions' ,'admin\InstitutionsController');
    Route::resource('/members' ,'admin\MembersController');

    Route::resource('/game_categories' ,'admin\GameCategoriesController');
    Route::resource('/sports' ,'admin\SportsController');
    Route::resource('/games' ,'admin\GamesController');
    Route::get('/game_status' ,'admin\GamesController@game_status');

    Route::resource('/executive' ,'admin\IcrayyeController');
    Route::resource('/game_statistics' ,'admin\GameStatisticsController');
    Route::resource('/athlete' ,'admin\AthleteController');
    Route::get('/athlete_kommisia' ,'admin\AthleteController@kommisia');
    Route::get('/significance_status' ,'admin\AthleteController@significance_status');

    Route::resource('/tournaments' ,'admin\TurnirController');
    Route::resource('/athlete_statistics' ,'admin\AthleteStatisticsController');
    Route::get('/tournaments_type' ,'admin\AthleteStatisticsController@tournaments_type');
});

app/Icraye.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Icraye extends Model
{
  protected $table = 'icraye';
  protected $primaryKey = 'id';
  public $timestamps = false;
  protected $fillable = [
    'id',
    'title',
    'title_en',
    'description',
    'description_en',
  ];
}

resources/views/admin/icraye/create.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">

            <div class="header">
            </div>
            <div class="body table-responsive">
              <form class="form-horizontal" action="{{ route('executive.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="col-md-6">
                  <p><b>Səhifə başlığı  </b><span style="color:red;">* </span></p>
                  <input type="text" name="title"  class="form-control"  required>
                </div>
                <div class="col-md-6">
                  <p><b>Səhifə başlığı  (EN)</b><span style="color:red;"> </span></p>
                  <input type="text" name="title_en"  class="form-control"  >
                </div>
                <div class="col-md-6">
                  <p><b>Kontent<span style="color:red">*</span></b></p>
                  <textarea name="description" rows="8" cols="80" required id="article-ckeditor"></textarea>
                </div>
                <div class="col-md-6">
                  <p><b>Kontent (en)<span style="color:red"></span></b></p>
                  <textarea name="description_en" rows="8" cols="80" required id="article-ckeditor1"></textarea>
                </div>
                <div class="col-md-10">
                  <button type="submit" class="btn btn-success">
                      Əlavə Et
                    </button>
                </div>
              </form>
            </div>
        </div>
    </div>
</div>
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script type="text/javascript">
  CKEDITOR.replace( 'article-ckeditor' );
  CKEDITOR.replace( 'article-ckeditor1' );

  $("form").submit( function(e) {
     var messageLength = CKEDITOR.instances['article-ckeditor'].getData().replace(/<[^>]*>/gi, '').length;
     var messageLength1 = CKEDITOR.instances['article-ckeditor1'].getData().replace(/<[^>]*>/gi, '').length;
     if( messageLength < 1) {
         alert( 'İşarələnmiş bütün xanalar doldurulmalıdır' );
         e.preventDefault();
     }
 });
</script>
@endsection

resources/views/admin/icraye/edit.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">

            <div class="header">
            </div>
            <div class="body table-responsive">
              <form class="form-horizontal" action="{{ route('executive.update', $icraye->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                  <input type="hidden" name="_method" value="PATCH">
                  <div class="col-md-6">
                    <p><b>Səhifə başlığı  </b><span style="color:red;">* </span></p>
                    <input type="text" name="title"  class="form-control"  required value="{{$icraye->title}}">
                  </div>
                  <div class="col-md-6">
                    <p><b>Səhifə başlığı  (EN)</b><span style="color:red;"> </span></p>
                    <input type="text" name="title_en"  class="form-control"  value="{{$icraye->title_en}}">
                  </div>
                  <div class="col-md-6">
                    <p><b>Kontent<span style="color:red">*</span></b></p>
                    <textarea name="description" rows="8" cols="80" required id="article-ckeditor">{{$icraye->description}}</textarea>
                  </div>
                  <div class="col-md-6">
                    <p><b>Kontent (en)<span style="color:red"></span></b></p>
                    <textarea name="description_en" rows="8" cols="80" required id="article-ckeditor1">{{$icraye->description_en}}</textarea>
                  </div>
                <div class="col-md-10">
                  <button type="submit" class="btn btn-success">
                    Redaktə Et
                    </button>
                </div>
              </form>


            </div>
        </div>
    </div>
</div>
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script type="text/javascript">
  CKEDITOR.replace( 'article-ckeditor' );
  CKEDITOR.replace( 'article-ckeditor1' );

  $("form").submit( function(e) {
     var messageLength = CKEDITOR.instances['article-ckeditor'].getData().replace(/<[^>]*>/gi, '').length;
     var messageLength1 = CKEDITOR.instances['article-ckeditor1'].getData().replace(/<[^>]*>/gi, '').length;
     if( messageLength < 1) {
         alert( 'İşarələnmiş bütün xanalar doldurulmalıdır' );
         e.preventDefault();
     }
 });
</script>
@endsection

resources/views/admin/icraye/index.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            @if(Session::has('mesaj'))
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                {{ Session::get('mesaj') }}
            </div>
            @endif
            <div class="header">
                <h2>
                <a href="{{ route('executive.create') }}"><button type="button" class="btn btn-success btn-circle waves-effect waves-circle waves-float">
                    <i class="material-icons">add</i>
                </button></a>
            </div>
            <div class="body table-responsive">


              <table class="table table-hover">
                  <thead>
                      <tr>
                          <th>Səhifə başlığı </th>
                          <th><span class="text-danger">Sil</span> / <span class="text-success">Redaktə et</span></th>
                      </tr>
                  </thead>
                  <tbody>
                      @foreach($icraye as $cate)
                      <tr>

                          <td>{{ $cate->title }}</td>
                          <td>
                              <form action="{{ route('executive.destroy', $cate->id) }}" method="post" style="display: initial;">
                                  {{ csrf_field() }}
                                  <input type="hidden" name="_method" value="DELETE">
                                  <input type="submit" value="Sil" class="btn btn-danger">
                              </form>
                              <a href="{{ route('executive.edit', $cate->id) }}" class="btn-success btn">Redaktə et</a>
                          </td>
                      </tr>
                      @endforeach
                  </tbody>
              </table>





            </div>
        </div>
    </div>
</div>
@endsection