routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'IndexController@index');


Route::get('/articles', 'NewsController@news');
Route::get('/news/{id}', 'NewsController@news_detalis');
Route::get('/news-archive', 'NewsController@news_archive');
Route::get('/news-search', 'NewsController@news_search');


Route::get('/activity', 'NewsController@activity');
Route::get('/activities', 'NewsController@activities');
Route::get('/activity/{id}', 'NewsController@activity_detalis');
Route::get('/programs', 'NewsController@programs');
Route::get('/programs/{id}', 'NewsController@program_detalis');
Route::get('/galleries', 'GalleryController@galleries');
Route::get('/gallery/{id}', 'GalleryController@gallery_detalis');
Route::get('/videos/{id}', 'GalleryController@video_detalis');
Route::get('/game-categories', 'GameController@game_categories');
Route::get('/game-categories/{id}', 'GameController@games');
Route::get('/game/{id}', 'GameController@games_detalis');
Route::get('/partners', 'PartnersController@partners');
Route::get('/partner/{id}', 'PartnersController@partner_detalis');
Route::get('/about', 'AboutController@about');
Route::get('/athletes', 'AthleteController@index');
Route::get('/athlete/{id}', 'AthleteController@detailis');
Route::get('/athletes/filters', 'AthleteController@athlete_filter');
Route::get('/sports', 'AthleteController@sports');

Route::get('/locale/{lang}', 'IndexController@setLocale');
Route::post('/subscribe', 'ContactController@subscribe');

// Route::get('/test_view', 'IndexController@test');
// Route::get('/tokyo2020', function(){
//     return view('front.tokyo2020');
// });

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::resource('gallery' ,'admin\GalleryController');
    Route::get('/imgs/{id}/del' ,'admin\GalleryController@del');
    Route::post('/update_img' ,'admin\GalleryController@update_img');
    Route::post('/create_img' ,'admin\GalleryController@create_img');

    Route::resource('videogallery' ,'admin\VideoGalleryController');
    Route::resource('publications' ,'admin\PublicationsController');

    Route::resource('news' ,'admin\NewsController');
    Route::get('/news_imgs/{id}/del' ,'admin\NewsController@del');
    Route::post('/news_update_img' ,'admin\NewsController@update_img');
    Route::post('/news_create_img' ,'admin\NewsController@create_img');

    Route::resource('/federations' ,'admin\FederationsController');
    Route::resource('/documents' ,'admin\DocumentsController');
    Route::resource('/document_groups' ,'admin\DocumentGroupsController');
    Route::resource('/sponsors' ,'admin\SponsorsController');
    Route::resource('/partners' ,'admin\PartnersController');

    Route::resource('/persons' ,'admin\PersonsController');
    Route::get('/index_status','admin\PersonsController@index_status');
    Route::get('/icra_komite','admin\PersonsController@icra_komite');

    Route::resource('/history' ,'admin\HisrtoryController');
    Route::resource('/committees' ,'admin\CommitteeController');

    Route::resource('/bash_meclis' ,'admin\BasMeclisController');
    Route::get('/meclis/{id}/del' ,'admin\BasMeclisController@del');
    Route::get('/meclis/{id}/terkib_edit' ,'admin\BasMeclisController@terkib_edit');
    Route::get('/meclis/{id}/create' ,'admin\BasMeclisController@creat_ter');
    Route::post('/meclis/terkib_update' ,'admin\BasMeclisController@terkib_update');
    Route::post('/meclis/terkib_create' ,'admin\BasMeclisController@terkib_create');

    Route::resource('/institutions' ,'admin\InstitutionsController');
    Route::resource('/members' ,'admin\MembersController');

    Route::resource('/game_categories' ,'admin\GameCategoriesController');
    Route::resource('/sports' ,'admin\SportsController');
    Route::resource('/games' ,'admin\GamesController');
    Route::get('/game_status' ,'admin\GamesController@game_status');

    Route::resource('/executive' ,'admin\IcrayyeController');
    Route::resource('/game_statistics' ,'admin\GameStatisticsController');
    Route::resource('/athlete' ,'admin\AthleteController');
    Route::get('/athlete_kommisia' ,'admin\AthleteController@kommisia');
    Route::get('/significance_status' ,'admin\AthleteController@significance_status');

    Route::resource('/tournaments' ,'admin\TurnirController');
    Route::resource('/athlete_statistics' ,'admin\AthleteStatisticsController');
    Route::get('/tournaments_type' ,'admin\AthleteStatisticsController@tournaments_type');
});

resources/views/admin/fotogallery/create.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">

            <div class="header">
            </div>
            <div class="body table-responsive">
              <form class="form-horizontal" action="{{ route('gallery.store') }}" method="POST" enctype="multipart/form-data">
                @csrf


                <div class="col-md-6">
                  <p><b>Qallereya  Başlığı </b><span style="color:red;">* </span></p>
                  <input type="text" name="gallery_name"  class="form-control"  required>
                </div>
                <div class="col-md-6">
                  <p><b>Qallereya  Başlığı (EN)</b><span style="color:red;"> </span></p>
                  <input type="text" name="gallery_name_en"  class="form-control"  >
                </div>
                <div class="col-md-6">
                  <p><b>Qallereya Ön şəkli (Fayl ölçüsü max 1024kb olmalıdır (min:280x240))</b><span style="color:red;">* </span></p>
                  <input type="file" name="gallery_thubnail"  class="form-control"  required  id="logo">
                </div>
                <div class="col-md-6">
                  <p><b>Qallereya fotoları
                     (Fayl ölçüsü max 1024kb olmalıdır (min:1180x610))</b><span style="color:red;">* </span></p>
                  <input type="file" name="img_src[]"  class="form-control"  required  id="imgs" multiple>
                </div>




                <div class="col-md-10">
                  <button type="submit" class="btn btn-success">
                      Əlavə Et
                    </button>
                </div>
              </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

$('#logo').bind('change', function(event) {
  if ($(this).context.files[0].size/ 1024 > 1024) {
    $(this).replaceWith($(this).val('').clone(true));
    alert('Fayl 1024kb dan böyükdür');
  }
});
$('#imgs').bind('change', function(event) {
  var length = $(this).context.files.length
   for (var i = 0; i < length; i++) {
     if ($(this).context.files[i].size/ 1024 > 1024) {
       $(this).replaceWith($(this).val('').clone(true));
       alert('Fayl 1024kb dan böyükdür');
     }
   }
});
</script>
@endsection

resources/views/admin/fotogallery/edit.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">

            <div class="header">
            </div>
            <div class="body table-responsive">
              <form class="form-horizontal" action="{{ route('gallery.update', $gallery->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                  <input type="hidden" name="_method" value="PATCH">
                  <div class="col-md-6">
                    <p><b>Qallereya  Başlığı </b><span style="color:red;">* </span></p>
                    <input type="text" name="gallery_name"  class="form-control"  required value="{{$gallery->gallery_name}}">
                  </div>
                  <div class="col-md-6">
                    <p><b>Qallereya  Başlığı (EN)</b><span style="color:red;"> </span></p>
                    <input type="text" name="gallery_name_en"  class="form-control"   value="{{$gallery->gallery_name_en}}">
                  </div>
              
                <div class="col-md-12" >
                  <p><b>Qallereya Ön şəkli </b><br><span style="color:red;">(Fayl ölçüsü max 1024kb olmalıdır (min:280x240))</span></p>
                  <input type="file" name="gallery_thubnail"  class="form-control" id="cover" style="display:n one;">
                  <div class="col-md-3" style="padding-top:40px;">
                    <label for="cover"><img src="/uploads/{{$gallery->gallery_thubnail}}" class="img-responsive" style="cursor:pointer"/></label>
                    <!-- <p><b>İşə aid şəkillər (Eyni anda max 10 şəkil əlavə edilə bilər)</b></p>
                    <input type="file" name="img_src[]" multiple class="form-control"> -->
                  </div>
                </div>


                <div class="col-md-10">
                  <button type="submit" class="btn btn-success">
                    Redaktə Et
                    </button>
                </div>
              </form>


            </div>
        </div>
    </div>
</div>

     <script type="text/javascript">
  
    $('#cover, #intro').bind('change', function(event) {
      if ($(this).context.files[0].size/ 1024 > 1024) {
        $(this).replaceWith($(this).val('').clone(true));
        alert('Fayl 1024kb dan böyükdür');
      }
    });
     </script>
@endsection

resources/views/admin/fotogallery/index.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            @if(Session::has('mesaj'))
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                {{ Session::get('mesaj') }}
            </div>
            @endif
            <div class="header">
                <h2>
                <a href="{{ route('gallery.create') }}"><button type="button" class="btn btn-success btn-circle waves-effect waves-circle waves-float">
                    <i class="material-icons">add</i>
                </button></a>
            </div>
            <div class="body table-responsive">


              <table class="table table-hover">
                  <thead>
                      <tr>
                          <th>Qallereya adı</th>
                          <th>Şəkillər</th>
                          <th><span class="text-danger">Sil</span> / <span class="text-success">Redaktə et</span></th>
                      </tr>
                  </thead>
                  <tbody>
                      @foreach($gallerys as $gallery)
                      <tr>

                          <td>{{ $gallery->gallery_name }}</td>

                          <td><a href="{{ route('gallery.show', $gallery->id) }}" class="btn-primary btn">Şəkillər</a></td>
                          <td>
                            <button value="{{$gallery->id}}" class="btn btn-danger remove">Sil</button>
                              <form id="remove{{$gallery->id}}" style="display: none" action="{{ route('gallery.destroy', $gallery->id) }}" method="post" style="display: initial;">
                                  {{ csrf_field() }}
                                  <input type="hidden" name="_method" value="DELETE">
                                  <input type="submit" value="Sil" class="btn btn-danger">
                              </form>
                              <a href="{{ route('gallery.edit', $gallery->id) }}" class="btn-success btn">Redaktə et</a>
                          </td>
                      </tr>
                      @endforeach
                  </tbody>
              </table>





            </div>
        </div>
    </div>
</div>
<script>

    $('.remove').on('click', function(){
        var val = $(this).val();
        const swalWithBootstrapButtons = Swal.mixin({
        customClass: {
        confirmButton: 'btn btn-success',
        cancelButton: 'btn btn-danger'
         },
      buttonsStyling: false
    })
    
    swalWithBootstrapButtons.fire({
      title: 'Əminsiniz?',
      text: "Qalereyaya aid bütün şəkillər silinəcək",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonText: 'Bəli, Sil!',
      cancelButtonText: 'Ləğv et!',
      reverseButtons: true
    }).then((result) => {
      if (result.isConfirmed) {
        $('#remove'+val+'').submit();
       
      } else if (
        /* Read more about handling dismissals below */
        result.dismiss === Swal.DismissReason.cancel
      ) {
        swalWithBootstrapButtons.fire(
          'Ləğv edildi',
        )
      }
    })
    });
    </script>
@endsection

resources/views/admin/fotogallery/show.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            @if(Session::has('mesaj'))
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                {{ Session::get('mesaj') }}
            </div>
            @endif
            <div class="header">
                <h2>
                <a href="{{ route('gallery.index') }}"><button type="button" class="btn btn-success btn-circle waves-effect waves-circle waves-float">
                  <i class="material-icons">keyboard_backspace</i>
                </button></a>
            </div>
            <div class="body table-responsive">


                      @foreach($gallery->gallery_images as $port)
                            <div class="col-md-3">
                              <img src="/uploads/{{$port->img_src}}" alt="" style="width:100%;margin-bottom:10px;">


                                <div class="" style="margin-bottom:10px;">
                                  <button class="btn btn-success open_form" data-id="{{$port->id}}">Redaktə et</button>
                                  <a href="/admin/imgs/{{$port->id}}/del" class="btn-danger btn">Sil</a>
                                </div>
                                <form action="/admin/update_img" method="post"  enctype="multipart/form-data" class="forms" style="display:none;" id="{{$port->id}}">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="img_id" value="{{$port->id}}">
                                    <input type="file" name="img_file" style="width:100%;">
                                    <button type="submit" class="btn btn-primary" style="margin-top:15px;">Əlavə et</button>

                                </form>
                            </div>

                      @endforeach
                        <form  action="/admin/create_img" method="post" enctype="multipart/form-data" class="col-md-3">
                          @csrf
                          <input type="hidden" name="gallery_id" value="{{$id}}">
                          <label for="" style="color:red">Fayl ölçüsü max 1024kb olmalıdır</label>
                          <input type="file" name="img_src" value="" required id="img">
                          <button type="submit" name="button" class="btn btn-success" style="margin-top:10px;">Əlavə et</button>
                        </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
  $('.open_form').click(function(event) {
    $('.forms').hide();

    var id = $(this).data('id');
    $('#'+id).slideDown();

  });

  $('#img').bind('change', function(event) {
    if ($(this).context.files[0].size/ 1024 > 1024) {
      $(this).replaceWith($(this).val('').clone(true));
      alert('Fayl 1024kb dan böyükdür');
    }
  });

</script>
@endsection